class DefaultEventhandlers;
class CfgPatches
{
	class Taliban_fighters
	{
		units[]=
		{
			"TBan_Warlord",
			"Afghan_Civilian6NH",
			"Afghan_Civilian6",
			"Afghan_Civilian5",
			"Afghan_Civilian4",
			"Afghan_Civilian3",
			"Afghan_Civilian2",
			"Afghan_Civilian1",
			"Afghan_Civilian3NH",
			"Afghan_Civilian2NH",
			"Afghan_Civilian1NH",
			"Tban_O_Offroad_01_F",
			"Tban_O_Transport_01_F",
			"TBan_Fighter6NH",
			"TBan_Fighter6",
			"TBan_Fighter5",
			"TBan_Fighter4",
			"TBan_Fighter3NH",
			"TBan_Fighter2NH",
			"TBan_Fighter1NH",
			"TBan_Fighter3",
			"TBan_Fighter2",
			"TBan_Fighter1",
			"TBan_Recruit6",
			"TBan_Recruit6NH",
			"TBan_Recruit5",
			"TBan_Recruit4",
			"TBan_Recruit3NH",
			"TBan_Recruit3",
			"TBan_Recruit2NH",
			"TBan_Recruit2",
			"TBan_Recruit1",
			"TBan_Recruit1NH"
		};
		weapons[]={};
		requiredVersion=1.5;
		requiredAddons[]=
		{
			"A3_Characters_F",
			"A3_Data_F",
			"A3_Soft_F"
		};
	};
};
class CfgVehicleClasses
{
	class TBan
	{
		displayName="Terrorists";
	};
	class AFGCIV
	{
		displayName="Muslims";
	};
};
class CfgFactionClasses
{
	class AFGCIV
	{
		displayName="Muslims";
		flag="\Taliban_fighters\data\Flags\flag_afghanistan_co.paa";
		icon="\Taliban_fighters\data\cfgfactionclasses_afgciv.paa";
		priority=1;
		side=3;
	};
	class Tban
	{
		displayName="Terrorists";
		flag="\Taliban_Fighters\data\Aggressor\flag_taliban_co.paa";
		icon="\Taliban_Fighters\data\cfgfactionclasses_Tban.paa";
		priority=1;
		side=0;
	};
};
class CfgVehicles
{
	class O_Soldier_base_F;
	class TBan_Fighter1: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Leader";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_akms",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		uniformClass="U_Afghan01";
	};
	class TBan_Fighter1NH: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Leader (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		uniformClass="U_Afghan01NH";
	};
	class TBan_Fighter2: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Fighter2NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		uniformClass="U_Afghan02NH";
	};
	class TBan_Fighter3: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Fighter3NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 2 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		uniformClass="U_Afghan03NH";
	};
	class TBan_Fighter4: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter4";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 3";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		uniformClass="U_Afghan04";
	};
	class TBan_Fighter5: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 4";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class TBan_Fighter6: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 5";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akms",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		uniformClass="U_Afghan06";
	};
	class TBan_Fighter6NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Fighter 5 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		uniformClass="U_Afghan06NH";
	};
	class TBan_Warlord: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Warlord";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class Haji_Matin: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"Nikos",
			"NoGlasses"
		};
		displayName="Terrorist HVT";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_makarov_pmm",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Recruit: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist PKM 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_vydra_3m"
		};
		respawnLinkedItems[]=
		{
			"rhs_vydra_3m"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		uniformClass="U_Afghan01";
	};
	class TBan_Recruit1NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist PKM 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_vydra_3m"
		};
		respawnLinkedItems[]=
		{
			"rhs_vydra_3m"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		uniformClass="U_Afghan01NH";
	};
	class TBan_Recruit2: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist PKM 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_vydra_3m"
		};
		respawnLinkedItems[]=
		{
			"rhs_vydra_3m"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Recruit2NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist PKM 2 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=20;
		backpack="";
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_vydra_3m"
		};
		respawnLinkedItems[]=
		{
			"rhs_vydra_3m"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		uniformClass="U_Afghan02NH";
	};
	class TBan_Recruit3: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Sniper 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Recruit3NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Sniper 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=25;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		uniformClass="U_Afghan03NH";
	};
	class TBan_Recruit4: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter4";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist Sniper 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=35;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_svd_pso1",
			"rhs_weap_makarov_pmm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		uniformClass="U_Afghan04";
	};
	class TBan_Recruit5: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist PKM 3";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=25;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo"
		};
		linkedItems[]=
		{
			"rhs_vydra_3m"
		};
		respawnLinkedItems[]=
		{
			"rhs_vydra_3m"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class TBan_Recruit6: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist RPG 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_rpg7",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_rpg7",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo",
			"rhs_rpg7_PG7VL_mag"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo",
			"rhs_rpg7_PG7VL_mag"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		uniformClass="U_Afghan06";
	};
	class TBan_Recruit6NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Terrorist RPG 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_rpg7",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_akm",
			"rhs_weap_rpg7",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo",
			"rhs_rpg7_PG7VL_mag"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_mag_rdg2_white",
			"rhs_mag_rdg2_white",
			"rhs_mag_rgo",
			"rhs_mag_rgo",
			"rhs_rpg7_PG7VL_mag"
		};
		linkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		respawnLinkedItems[]=
		{
			"rhs_6sh92_digi"
		};
		model="\Taliban_Fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		uniformClass="U_Afghan06NH";
	};
	class Afghan_civilian1: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Village Leader";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01";
	};
	class Afghan_civilian1NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Village Leader (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01NH";
	};
	class Afghan_Civilian2: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 1";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02";
	};
	class Afghan_Civilian2NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 1 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02NH";
	};
	class Afghan_civilian3: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 2";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03";
	};
	class Afghan_civilian3NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 2 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03NH";
	};
	class Afghan_Civilian4: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian4";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 3";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan04";
	};
	class Afghan_Civilian5: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian5";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 4";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan05";
	};
	class Afghan_Civilian6: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 5";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06";
	};
	class Afghan_Civilian6NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Muslim Civilian 5 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06NH";
	};
	class rhs_uaz_dshkm_base;
	class Tban_O_Offroad_01_F: rhs_uaz_dshkm_base
	{
		dlc="u100";
		scope=2;
		side=0;
		Displayname="Terrorist Technical";
		faction="Tban";
		forceInGarage=1;
		crew="TBan_Fighter2";
		author="EricJ";
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=10;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_ToolKit
			{
				name="ToolKit";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_AKMags
			{
				magazine="rhs_30Rnd_762x39mm";
				count=16;
			};
		};
		animationList[]=
		{
			"light_hide",
			1
		};
	};
	class rhs_gaz66_vmf;
	class Tban_O_Transport_01_F: rhs_gaz66_vmf
	{
		scope=2;
		side=0;
		Displayname="Terrorist Truck";
		faction="Tban";
		forceInGarage=1;
		crew="TBan_Recruit5";
		author="EricJ";
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=10;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_ToolKit
			{
				name="ToolKit";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_AKMags
			{
				magazine="rhs_30Rnd_762x39mm";
				count=16;
			};
		};
	};
};
class CfgWeapons
{
	class ItemInfo;
	class InventoryItem_Base_F;
	class UniformItem: InventoryItem_Base_F
	{
		type=801;
	};
	class ItemCore;
	class Uniform_Base;
	class U_Afghan01: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 1";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_01.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter1";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan02: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 2";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter2";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan03: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 3";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_03.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter3";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan04: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 4";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_04.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil04_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter4";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan05: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 5";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_05.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil05_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter5";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan06: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 6";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_06.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter6";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan01NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 1 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_01NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter1NH";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan02NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 2 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_02NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter2NH";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan03NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 3 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_03NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter3NH";
			passThrough=1;
			containerClass="Supply30";
			mass=30;
		};
	};
	class U_Afghan06NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Musilm Clothes 6 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_06NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter6NH";
			armor=0;
			passThrough=1;
			containerClass="Supply30";
			mass=30;
		};
	};
	class H_HelmetB;
	class Afghan_01Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 1";
		picture="\Taliban_Fighters\data\ui\Afghan_01Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_01Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_01Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			armor=0;
			passThrough=1;
		};
	};
	class Afghan_02Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 2";
		picture="\Taliban_Fighters\data\ui\Afghan_02Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_02Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_02Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_03Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 3";
		picture="\Taliban_Fighters\data\ui\Afghan_03Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_03Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_03Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_04Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 4";
		picture="\Taliban_Fighters\data\UI\Afghan_04Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_04Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil04_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_04Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_05Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 5";
		picture="\Taliban_Fighters\data\UI\Afghan_05Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_05Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil05_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_05Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_06Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Musilm Hat 6";
		picture="\Taliban_Fighters\data\ui\Afghan_06Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_06Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_06Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
};
class CfgGroups
{
	class EAST
	{
		name="OPFOR";
		class TBan_Group
		{
			name="Terrorists";
			class Infantry
			{
				name="Men";
				class TBan_Squad
				{
					name="8 Man Squad";
					faction="Tban";
					rarityGroup=0.80000001;
					class Unit0
					{
						side=0;
						vehicle="TBan_Fighter1";
						rank="SERGEANT";
						position[]={0,3,0};
						skill=1;
					};
					class Unit1
					{
						side=0;
						vehicle="TBan_Fighter2";
						rank="PRIVATE";
						position[]={1,0,0};
						skill=1;
					};
					class Unit2
					{
						side=0;
						vehicle="TBan_Fighter3";
						rank="PRIVATE";
						position[]={3,0,0};
						skill=1;
					};
					class Unit3
					{
						side=0;
						vehicle="TBan_Fighter4";
						rank="PRIVATE";
						position[]={5,0,0};
						skill=1;
					};
					class Unit4
					{
						side=0;
						vehicle="TBan_Recruit1NH";
						rank="PRIVATE";
						position[]={7,0,0};
						skill=1;
					};
					class Unit5
					{
						side=0;
						vehicle="TBan_Fighter5";
						rank="PRIVATE";
						position[]={9,0,0};
						skill=1;
					};
					class Unit6
					{
						side=0;
						vehicle="TBan_Recruit3";
						rank="PRIVATE";
						position[]={11,0,0};
						skill=1;
					};
					class Unit7
					{
						side=0;
						vehicle="TBan_Recruit6NH";
						rank="PRIVATE";
						position[]={13,0,0};
						skill=1;
					};
				};
			};
			class Motorized
			{
				name="Wheeled";
				class TBan_Truck
				{
					name="QRF";
					side=0;
					faction="Tban";
					class Unit0
					{
						side=0;
						vehicle="Tban_O_Transport_01_F";
						rank="SERGEANT";
						position[]={0,3,0};
					};
					class Unit1
					{
						side=0;
						vehicle="TBan_Fighter2";
						rank="PRIVATE";
						position[]={1,0,0};
						skill=1;
					};
					class Unit2
					{
						side=0;
						vehicle="TBan_Fighter3";
						rank="PRIVATE";
						position[]={3,0,0};
						skill=1;
					};
					class Unit3
					{
						side=0;
						vehicle="TBan_Fighter4";
						rank="PRIVATE";
						position[]={5,0,0};
						skill=1;
					};
					class Unit4
					{
						side=0;
						vehicle="TBan_Recruit1NH";
						rank="PRIVATE";
						position[]={7,0,0};
						skill=1;
					};
					class Unit5
					{
						side=0;
						vehicle="TBan_Fighter5";
						rank="PRIVATE";
						position[]={9,0,0};
						skill=1;
					};
					class Unit6
					{
						side=0;
						vehicle="TBan_Recruit3";
						rank="PRIVATE";
						position[]={11,0,0};
						skill=1;
					};
					class Unit7
					{
						side=0;
						vehicle="TBan_Recruit6NH";
						rank="PRIVATE";
						position[]={13,0,0};
						skill=1;
					};
				};
			};
		};
	};
};
class cfgMods
{
	author="EricJ [TF Blackheart]";
	timepacked="1449766140";
};
